input:
  kafka:
    addresses:
      - ${FLEXPRICE_KAFKA_BROKERS}

    topics:
      - ${FLEXPRICE_KAFKA_TOPIC:bento-testing}

    consumer_group: ${FLEXPRICE_KAFKA_CONSUMER_GROUP:bento-raw-clickhouse-v1}
    start_from_oldest: true

    tls:
      enabled: true

    sasl:
      mechanism: ${FLEXPRICE_KAFKA_SASL_MECHANISM:PLAIN}
      user: ${FLEXPRICE_KAFKA_SASL_USER}
      password: ${FLEXPRICE_KAFKA_SASL_PASSWORD}

    client_id: ${FLEXPRICE_KAFKA_CLIENT_ID:bento-raw-clickhouse}

    commit_period: 1s
    max_processing_period: 100ms
    fetch_buffer_cap: ${KAFKA_FETCH_BUFFER_CAP:20}
    checkpoint_limit: ${KAFKA_CHECKPOINT_LIMIT:20}

pipeline:
  processors:
    # ---- Basic validation ----
    - mapping: |
        let valid = (
          this.id != null && this.id != "" &&
          this.orgId != null && this.orgId != "" &&
          this.createdAt != null && this.createdAt != ""
        )
        root = if $valid { this } else { deleted() }

    # ---- Normalize + build raw payload ----
    - mapping: |
        root = {}

        root.id = this.id.string()
        root.tenant_id = env("FLEXPRICE_TENANT_ID").string().or("")
        root.environment_id = env("FLEXPRICE_ENVIRONMENT_ID").string().or("")
        root.external_customer_id = this.orgId.string()
        root.source = this.targetItemId.string().or("")
        root.timestamp = this.createdAt.string()

        # ---- Build event_name SAFELY ----
        root.event_name = ""

        if this.providerName.string().or("") != "" {
          root.event_name = this.providerName.string().trim().lowercase()
        } else if this.serviceName.string().or("") != "" {
          root.event_name = this.serviceName.string().trim().lowercase()
        }

        if this.methodName.string().or("") != "" {
          if this.methodName.string() == "BEDROCK_LLM" {
            root.event_name = root.event_name + "-modeling"
          } else {
            root.event_name = root.event_name + "-" + this.methodName.string().trim().lowercase()
          }
        }

        if this.data.modelName.string().or("") != "" {
          root.event_name = root.event_name + "-" + this.data.modelName.string().trim().lowercase()
        }

        # ---- Raw payload ----
        root.payload = this.string()

        # ---- Flexible analytics fields ----
        root.field1 = this.providerName.string().or("")
        root.field2 = this.data.modelName.string().or("")
        root.field3 = this.methodName.string().or("")
        root.field4 = this.byok.string().or("")
        root.field5 = this.dataInterface.string().or("")
        root.field6 = this.referenceType.string().or("")
        root.field7 = this.targetItemType.string().or("")
        root.field8 = this.targetItemId.string().or("")

output:
  sql_insert:
    driver: clickhouse
    
    # Use native ClickHouse protocol (port 9000) - more efficient than HTTP
    # Password is URL-encoded to handle special characters (?, ;, !)
    dsn: "clickhouse://${FLEXPRICE_CLICKHOUSE_USERNAME}:98eA22lu%3FP%3BQ%21A@${FLEXPRICE_CLICKHOUSE_ADDRESS}/${FLEXPRICE_CLICKHOUSE_DATABASE}"
    
    table: flexprice.raw_events
    
    columns:
      - id
      - tenant_id
      - environment_id
      - external_customer_id
      - event_name
      - source
      - payload
      - field1
      - field2
      - field3
      - field4
      - field5
      - field6
      - field7
      - field8
      - timestamp
    
    args_mapping: |
      root = [
        this.id,
        this.tenant_id,
        this.environment_id,
        this.external_customer_id,
        this.event_name,
        this.source,
        this.payload,
        this.field1,
        this.field2,
        this.field3,
        this.field4,
        this.field5,
        this.field6,
        this.field7,
        this.field8,
        this.timestamp
      ]
    
    # 🔥 BATCH + ASYNC CONFIG (IMPORTANT)
    batching:
      count: 1000        # 500–1000 batch size (use 500 if traffic is low)
      period: 1s         # flush every second even if batch not full
      jitter: 0.1        # avoids thundering herd
    
    max_in_flight: 8     # 8 parallel async inserts to ClickHouse

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  add_timestamp: true
