input:
  kafka:
    addresses:
      - ${FLEXPRICE_KAFKA_BROKERS}

    topics:
      - ${FLEXPRICE_KAFKA_TOPIC:bento-testing}

    consumer_group: ${FLEXPRICE_KAFKA_CONSUMER_GROUP:bento-billing-flexprice-v1}
    start_from_oldest: true

    tls:
      enabled: true

    sasl:
      mechanism: PLAIN
      user: ${FLEXPRICE_KAFKA_SASL_USER}
      password: ${FLEXPRICE_KAFKA_SASL_PASSWORD}

    client_id: ${FLEXPRICE_KAFKA_CLIENT_ID:bento-billing-collector}

    commit_period: 1s
    max_processing_period: 100ms
    fetch_buffer_cap: 256
    checkpoint_limit: 1000

pipeline:
  processors:
    - mapping: |
        # Preserve the raw original message (safe for DLQ/debug)
        meta.original_event = content().string()
        meta.original_topic = meta("kafka_topic")
        meta.original_partition = meta("kafka_partition")
        meta.original_offset = meta("kafka_offset")

        let valid = (
          this.orgId != null && this.orgId != "" &&
          this.targetItemType != null && this.targetItemType != "" &&
          this.methodName != null && this.methodName != "" &&
          this.providerName != null && this.providerName != "" &&
          this.id != null && this.id != "" &&
          this.startedAt != null && this.startedAt != "" &&
          this.key != null && this.key != ""
        )

        root = if $valid { this } else { deleted() }

    - mapping: |
        root = {}

        root.external_customer_id = this.orgId.string()
        root.event_name = this.targetItemType.string() + "-" + this.methodName.string() + "-" + this.providerName.string()
        root.event_id = this.id.string()
        root.timestamp = this.startedAt.string()
        root.source = this.key.string()

        # Start with `data` fields (stringify values; objects/arrays become JSON strings)
        root.properties = if this.data != null && this.data.type() == "object" {
          this.data.map_each(v -> v.string())
        } else {
          {}
        }

        # Add selected top-level fields into properties
        if this.byok != null {
          root.properties.byok = this.byok.string()
        }
        if this.dataInterface != null { root.properties.dataInterface = this.dataInterface.string() }
        if this.serviceName != null { root.properties.serviceName = this.serviceName.string() }
        if this.methodName != null { root.properties.methodName = this.methodName.string() }
        if this.targetItemType != null { root.properties.targetItemType = this.targetItemType.string() }
        if this.targetItemId != null { root.properties.targetItemId = this.targetItemId.string() }
        if this.referenceType != null { root.properties.referenceType = this.referenceType.string() }
        if this.referenceId != null { root.properties.referenceId = this.referenceId.string() }
        if this.createdAt != null { root.properties.createdAt = this.createdAt.string() }
        if this.updatedAt != null { root.properties.updatedAt = this.updatedAt.string() }
        if this.endedAt != null { root.properties.endedAt = this.endedAt.string() }

    - log:
        level: INFO
        message: |
          [KAFKA→FLEXPRICE] Processing BillingEntry:
          - Event Name: ${!json("event_name")}
          - Customer ID: ${!json("external_customer_id")}
          - Event ID: ${!json("event_id")}
          - Timestamp: ${!json("timestamp")}
          - Source: ${!json("source")}
          - Properties: ${!json("properties")}

output:
  flexprice:
    api_host: ${FLEXPRICE_API_HOST}
    api_key: ${FLEXPRICE_API_KEY}
    scheme: https

    batching:
      count: ${FLEXPRICE_BATCH_SIZE:10}
      period: ${FLEXPRICE_BATCH_PERIOD:2s}

    max_in_flight: ${FLEXPRICE_MAX_IN_FLIGHT:10}

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  add_timestamp: true
